# Generated by Django 3.0.5 on 2020-05-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
