# Generated by Django 3.0.5 on 2020-05-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioo', '0002_auto_20200507_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='cat_id',
            new_name='category',
        ),
    ]
