# Generated by Django 3.0.5 on 2020-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioo', '0003_auto_20200507_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
