# Generated by Django 3.0.5 on 2020-05-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioo', '0004_auto_20200507_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
