# Generated by Django 3.0.5 on 2020-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioo', '0005_auto_20200507_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
