# Generated by Django 3.0.5 on 2020-05-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioo', '0006_auto_20200508_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, default='images/work/05.jpg', null=True, upload_to=''),
        ),
    ]
