# Generated by Django 3.0.5 on 2020-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Your Location')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Number')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
