# Generated by Django 3.0.5 on 2020-05-16 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Line Of Text in Homepage')),
                ('second', models.CharField(blank=True, max_length=100, null=True, verbose_name='Second Line Of Text in Homepage')),
                ('third', models.CharField(blank=True, max_length=100, null=True, verbose_name='Third Line Of Text in Homepage')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
    ]
