# Generated by Django 3.0.5 on 2020-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Line Of Text in Homepage')),
                ('second', models.CharField(blank=True, max_length=100, null=True, verbose_name='Second Line Of Text in Homepage')),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
    ]
