# Generated by Django 3.0.5 on 2020-05-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='third',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Third Line Of Text in Homepage'),
        ),
    ]
