# Generated by Django 3.0.5 on 2020-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Write About You')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Upload Your Image')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name Of Client')),
                ('image', models.ImageField(blank=True, null=True, upload_to='client/', verbose_name='Upload Client Image/Logo')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Link Of Client')),
            ],
            options={
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Icon Name')),
                ('fact_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fact Title')),
                ('count', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fact total Number')),
            ],
            options={
                'verbose_name_plural': 'Fact',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Client Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testonomial/', verbose_name='Upload Client Image')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Client Words')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title Of Your Service')),
                ('service_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Icon Name')),
                ('service_des', models.TextField(blank=True, null=True, verbose_name='Service Detail')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
    ]
