# Generated by Django 3.0.5 on 2020-05-16 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='work_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Duration')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('post', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Description About Job')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work History',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical Skill Name')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rate Your Skill')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Technical Skill',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Name')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rate Your Skill')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='resume_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collage Timeline Date')),
                ('collage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collage Name')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collage Course')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Description About Degree')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resume Study',
            },
        ),
        migrations.CreateModel(
            name='cv_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Link Of Your Resume')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
