# Generated by Django 3.0.5 on 2020-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cv_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Link Of Your Resume')),
            ],
        ),
        migrations.CreateModel(
            name='resume_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Icon Name')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collage Timeline Date')),
                ('collage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collage Name')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Collage Course')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Description About Degree')),
            ],
            options={
                'verbose_name_plural': 'Resume Study',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Name')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rate Your Skill')),
            ],
            options={
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical Skill Name')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rate Your Skill')),
            ],
            options={
                'verbose_name_plural': 'Technical Skill',
            },
        ),
        migrations.CreateModel(
            name='work_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Icon Name')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Duration')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('post', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Description About Job')),
            ],
            options={
                'verbose_name_plural': 'Work History',
            },
        ),
    ]
