# Generated by Django 3.0.5 on 2020-05-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200507_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_study',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='work_history',
            name='icon',
        ),
    ]
