# Generated by Django 3.0.5 on 2020-05-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write First Name')),
                ('name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Last Name')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Phone Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='Upload Client Image')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Your Email')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
