# Generated by Django 3.0.5 on 2020-05-16 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write Phone Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload Client Image')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='Write gender')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
