# Generated by Django 3.0.5 on 2020-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='meuser',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='Upload Client Image'),
        ),
    ]
