# Generated by Django 3.0.5 on 2020-05-03 04:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20200502_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userprofile',
            new_name='Profile',
        ),
    ]
