# Generated by Django 3.0.5 on 2020-05-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200503_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='meuser',
            new_name='user',
        ),
    ]
