# Generated by Django 3.0.5 on 2020-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200503_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='man-logo.png', null=True, upload_to='profile/', verbose_name='Upload Client Image'),
        ),
    ]
