# Generated by Django 3.0.5 on 2020-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200505_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Upload Client Image'),
        ),
    ]
